### ISSUE TITLE
MCU-updated, 32-bit overflow

### ISSUE THREAD

**Issue by kivel** [epics-modules/ecmc#38]
IOCs forward linking from `${IOC}:MCU-updated` freeze once the value reaches 2.147.483.647.
After manually resetting the forward linked PV, the IOC recovers, but the value of the cycle counter (MCU-updated) is negative. Thus pointing towards an overflow.
Can the cycle counter be migrated to a 64-bit integer?

**Comment by anderssandstrom** [comment]
Thanks for reporting!
Yes the counter can be migrated to 64 bit int.
But, I don't understand why the forward link freeze? Any error message?
I will look into the issue.

**Comment by kivel** [comment]
No, it just stopped.


--
Paul Scherrer Institute
Dr. Niko Kivel
Forschungsstrasse 111
WBGB/017
5232 Villigen PSI
Switzerland

phone: +41 56 310 2226
email: niko.kivel@psi.ch
________________________________

**Comment by anderssandstrom** [comment]
Issue was concluded to be related to a database config error in a specific ioc, not related to ecmc.
