### ISSUE TITLE
NTM-field of motor record not behaving as documented

### ISSUE THREAD

**Issue by kivel** [epics-modules/ecmc#42]
This is with NTM==1

- Case 1: Motor moves 0-->100, user enters '0' again
result, Motor stops but does not go to Zero.

- Case 2: Motor moves 0-->100, user enters '50' (motor is at 25 at this moment)
result, Motor stops at 51 (slight overshoot) but does _not_ move to 50.
 
To me it seems as of the MR is calling the 'stop' but not issuing a new move command.

**Comment by kivel** [comment]
OK, but I can't file an issue there :)

**Comment by tboegi** [comment]
@kivel : The fix is here:
https://github.com/europeanspallationsource/motor/tree/210506-0611-fix-NTM

**Comment by tboegi** [comment]
Hej @kivel : The fix is here:
https://github.com/EuropeanSpallationSource/motor/commit/41c2bc5cc29cfaf4164ff50d067083dac1f96248
