### ISSUE TITLE
max velocity

### ISSUE THREAD

**Issue by kivel** [epics-modules/ecmc#47]
Since ECMC is able to operate w/o the motorRecord, a means to limit the maximum velocity should be available.

So far, it's possible to catch high velocity violations only via `monitoring`, which is nice, but always throws the axis into an error state.
The new feature should reject velocity setpoints above the specified upper limit.

**Comment by tboegi** [comment]
Note that the motorRecord will silently limit the velocity > max velocity:
If VELO > VMAX && VMAX != 0:
  VELO = VMAX

**Comment by kivel** [comment]
@tboegi , no, we are talking different things here :)
We are discussing how to handle setpoints outside the allowed range on the motion controller level, and or operation w/o motorRecord.
I assume the motion controller should also catch those violations when 'wrong' setpoints are originating from a PLC?

**Comment by kivel** [comment]
I can confirm that this works.

**Comment by anderssandstrom** [comment]
Ok, then I close this issue.
