### ISSUE TITLE
support multiple encoders per axis

### ISSUE THREAD

**Issue by kivel** [epics-modules/ecmc#48]
Add support for multiple encoders to the axis object. At least 2 should be supported.

Why? 
Twincat allows multiple encoders.. :)

**Comment by anderssandstrom** [comment]
@kivel added support for up to 8 encoders per axis. Please check here for more info of features:
* https://gitlab.esss.lu.se/epics-modules/ecmccfg/-/blob/master/examples/test/multi_encoder/readme.md
* https://github.com/epics-modules/ecmc/blob/master/RELEASE.md
Any other features in mind?
