### ISSUE TITLE
softlimits disobeyed in `MOVE_VEL` mode

### ISSUE THREAD

**Issue by kivel** [epics-modules/ecmc#52]
When operating in velocity mode, the softlimits are disobeyed.
At passing the respective softlimit, an error is raised, e.g. `ERROR_MON_SOFT_LIMIT_FWD_INTERLOCK`, but the axis is _not_ stopped.
However, after manual intervention, the axis is block in the direction of the violation. So in general the limits are operation, have no effect during a move.

**Comment by anderssandstrom** [comment]
@kivel,
The soft limits are used like "virtual" limit switches, triggering a stop when the soflimits are exceeded. I have tested and it seems to work for me. Were you able to reproduce the error?

**Comment by kivel** [comment]
@anderssandstrom this report was due to an error in the config that caused the axis to decelerate too slowly.
